/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerCliente;
import controller.ControllerProduto;
import controller.ControllerProdutosVendasProdutos;
import controller.ControllerVendas;
import controller.ControllerVendasCliente;
import controller.ControllerVendasProdutos;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelCliente;
import model.ModelProduto;
import model.ModelProdutosVendasProdutos;
import model.ModelVendas;
import model.ModelVendasClientes;
import model.ModelVendasProdutos;
import util.BLDatas;

/**
 *
 * @author geiba
 */
public class ViewVendas extends javax.swing.JFrame {

    ControllerCliente controllerCliente = new ControllerCliente();
    ModelCliente modelCliente = new ModelCliente();
    ArrayList<ModelCliente> listaModelCliente = new ArrayList<>();
    ControllerProduto controllerProdutos = new ControllerProduto();
    ModelProduto modelProdutos = new ModelProduto();
    ArrayList<ModelProduto> listaModelProdutos = new ArrayList<>();
    ArrayList<ModelVendasClientes> listaModelVendasClientes = new ArrayList<>();
    ControllerVendasCliente controllerVendasCliente = new ControllerVendasCliente();
    ControllerVendas controllerVendas = new ControllerVendas();
    ModelVendas modelVendas = new ModelVendas();
    BLDatas blDatas = new BLDatas();
    ControllerVendasProdutos controllerVendasProdutos = new ControllerVendasProdutos();
    ModelVendasProdutos modelVendasProdutos = new ModelVendasProdutos();
    ArrayList<ModelVendasProdutos> listaModelVendasProdutos = new ArrayList<>();
    ControllerProdutosVendasProdutos controllerProdutosVendasProdutos = new ControllerProdutosVendasProdutos();
    ModelProdutosVendasProdutos modelProdutosVendasProdutos = new ModelProdutosVendasProdutos();
    ArrayList<ModelProdutosVendasProdutos> listaModelProdutosVendasProdutos = new ArrayList<>();
    String alterarSalvar;

    /**
     * Creates new form ViewVendas
     */
    public ViewVendas() {
        initComponents();
        setLocationRelativeTo(null);
//      listarClientes();
//        listarProdutos();
//       preencherCodigoClientePeloCombobok();
//        preencherCodigoProdutoPeloCombobox();
        carregarVendas();
        desabilitaHabilitaCampos(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTbPCadastroConsutarExcluirAlterar = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbProdutosVenda = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jTfValorTotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jBtSalvar = new javax.swing.JButton();
        jBtCancelar = new javax.swing.JButton();
        jBtNovo = new javax.swing.JButton();
        jTfDesconto = new javax.swing.JFormattedTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTFCodigoProduto = new javax.swing.JTextField();
        jBtRemover = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        uJCBNomeDoCliente = new componentes.UJComboBox();
        uJCBoxNomeProduto = new componentes.UJComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jBTAdicionarProduto = new javax.swing.JButton();
        jTFCodigoCliente = new javax.swing.JTextField();
        jTFQuantidade = new javax.swing.JFormattedTextField();
        jTFNumeroVendas = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTbVendas = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jBtExcluir = new javax.swing.JButton();
        jBtAlterar = new javax.swing.JButton();
        jBtImprimir = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTfPesquisa = new javax.swing.JTextField();
        jBtPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vendas");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jTbProdutosVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód. Produto", "Nome Produto", "Qtd.", "Valor unitário", "Valor Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTbProdutosVenda);
        if (jTbProdutosVenda.getColumnModel().getColumnCount() > 0) {
            jTbProdutosVenda.getColumnModel().getColumn(0).setMinWidth(90);
            jTbProdutosVenda.getColumnModel().getColumn(0).setPreferredWidth(90);
            jTbProdutosVenda.getColumnModel().getColumn(0).setMaxWidth(90);
            jTbProdutosVenda.getColumnModel().getColumn(2).setMinWidth(50);
            jTbProdutosVenda.getColumnModel().getColumn(2).setPreferredWidth(50);
            jTbProdutosVenda.getColumnModel().getColumn(2).setMaxWidth(50);
            jTbProdutosVenda.getColumnModel().getColumn(3).setMinWidth(90);
            jTbProdutosVenda.getColumnModel().getColumn(3).setPreferredWidth(90);
            jTbProdutosVenda.getColumnModel().getColumn(3).setMaxWidth(90);
            jTbProdutosVenda.getColumnModel().getColumn(4).setMinWidth(90);
            jTbProdutosVenda.getColumnModel().getColumn(4).setPreferredWidth(90);
            jTbProdutosVenda.getColumnModel().getColumn(4).setMaxWidth(90);
        }

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTfValorTotal.setEditable(false);
        jTfValorTotal.setBackground(new java.awt.Color(255, 255, 102));
        jTfValorTotal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTfValorTotal.setForeground(new java.awt.Color(153, 0, 0));
        jTfValorTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTfValorTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTfValorTotalActionPerformed(evt);
            }
        });
        jPanel3.add(jTfValorTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(699, 33, 103, -1));

        jLabel6.setText("Valor total:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(699, 11, -1, -1));

        jLabel7.setText("Desconto:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 11, -1, -1));

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setPreferredSize(new java.awt.Dimension(791, 52));

        jBtSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/magens18X18/Save_64.png"))); // NOI18N
        jBtSalvar.setText("Salvar");
        jBtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtSalvarActionPerformed(evt);
            }
        });

        jBtCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/magens18X18/Cancel2-256.png"))); // NOI18N
        jBtCancelar.setText("Cancelar");
        jBtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCancelarActionPerformed(evt);
            }
        });

        jBtNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/magens18X18/New File-256.png"))); // NOI18N
        jBtNovo.setText("Novo");
        jBtNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 464, Short.MAX_VALUE)
                .addComponent(jBtSalvar)
                .addContainerGap())
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBtCancelar, jBtNovo, jBtSalvar});

        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtSalvar)
                    .addComponent(jBtNovo)
                    .addComponent(jBtCancelar))
                .addGap(8, 8, 8))
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 70, -1, -1));

        jTfDesconto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jTfDesconto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTfDescontoFocusLost(evt);
            }
        });
        jPanel3.add(jTfDesconto, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 33, 100, -1));

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nome do Cliente:");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 14, -1, -1));

        jLabel5.setText("Quantidade:");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 71, -1, -1));

        jLabel1.setText("Cód. Cliente:");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 14, -1, -1));

        jTFCodigoProduto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFCodigoProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFCodigoProdutoFocusLost(evt);
            }
        });
        jPanel5.add(jTFCodigoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 95, 91, -1));

        jBtRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/magens18X18/Minus-18.png"))); // NOI18N
        jBtRemover.setText("Remover");
        jBtRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtRemoverActionPerformed(evt);
            }
        });
        jPanel5.add(jBtRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(703, 92, -1, -1));

        jLabel3.setText("Número da Venda:");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 14, -1, -1));

        uJCBNomeDoCliente.setAutocompletar(true);
        uJCBNomeDoCliente.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                uJCBNomeDoClientePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanel5.add(uJCBNomeDoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 35, 507, -1));

        uJCBoxNomeProduto.setAutocompletar(true);
        uJCBoxNomeProduto.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                uJCBoxNomeProdutoPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanel5.add(uJCBoxNomeProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 95, 383, -1));

        jLabel4.setText("Cód. Produto:");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 71, -1, -1));

        jLabel9.setText("Nome do Produto:");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 71, -1, -1));

        jBTAdicionarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/magens18X18/Plus-18.png"))); // NOI18N
        jBTAdicionarProduto.setText("Adicionar");
        jBTAdicionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTAdicionarProdutoActionPerformed(evt);
            }
        });
        jPanel5.add(jBTAdicionarProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 92, -1, -1));

        jTFCodigoCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFCodigoCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFCodigoClienteFocusLost(evt);
            }
        });
        jTFCodigoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCodigoClienteActionPerformed(evt);
            }
        });
        jPanel5.add(jTFCodigoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 37, 91, -1));

        jTFQuantidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jTFQuantidade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel5.add(jTFQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 95, 68, -1));

        jTFNumeroVendas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFNumeroVendas.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jPanel5.add(jTFNumeroVendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 37, 162, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTbPCadastroConsutarExcluirAlterar.addTab("Cadastro", jPanel1);

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setToolTipText("");

        jTbVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome do Cliente", "Data"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTbVendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTbVendasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTbVendas);
        if (jTbVendas.getColumnModel().getColumnCount() > 0) {
            jTbVendas.getColumnModel().getColumn(0).setMinWidth(110);
            jTbVendas.getColumnModel().getColumn(0).setPreferredWidth(110);
            jTbVendas.getColumnModel().getColumn(0).setMaxWidth(110);
            jTbVendas.getColumnModel().getColumn(2).setMinWidth(150);
            jTbVendas.getColumnModel().getColumn(2).setPreferredWidth(150);
            jTbVendas.getColumnModel().getColumn(2).setMaxWidth(150);
        }

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jBtExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/magens18X18/delete-128.png"))); // NOI18N
        jBtExcluir.setText("Excluir");
        jBtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtExcluirActionPerformed(evt);
            }
        });

        jBtAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/magens18X18/Edit_128.png"))); // NOI18N
        jBtAlterar.setText("Alterar");
        jBtAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAlterarActionPerformed(evt);
            }
        });

        jBtImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/magens18X18/Printer-18x18.png"))); // NOI18N
        jBtImprimir.setText("Imprimir");
        jBtImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtExcluir)
                    .addComponent(jBtAlterar)
                    .addComponent(jBtImprimir))
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setText("Pesquisa:");

        jBtPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/magens18X18/Search-128(1).png"))); // NOI18N
        jBtPesquisar.setText("Pesquisar");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTfPesquisa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtPesquisar)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jBtPesquisar))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTbPCadastroConsutarExcluirAlterar.addTab("Consultar/Excluir/Alterar", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTbPCadastroConsutarExcluirAlterar)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTbPCadastroConsutarExcluirAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtNovoActionPerformed
         jBtSalvar.setEnabled(true);
        alterarSalvar = "salvar";
        limparFormulario();
        desabilitaHabilitaCampos(true);
        jBtAlterar.setEnabled(false);
        jBtExcluir.setEnabled(false);
        jBtImprimir.setEnabled(false);
        jBtPesquisar.setEnabled(false);
        jTFQuantidade.setText(String.valueOf(1));
        listarClientes();
        listarProdutos();
        preencherCodigoClientePeloCombobok();
        preencherCodigoProdutoPeloCombobox();
    }//GEN-LAST:event_jBtNovoActionPerformed

    private void jTfValorTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTfValorTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTfValorTotalActionPerformed

    private void jBtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtExcluirActionPerformed
        // TODO add your handling code here:
        int linha = jTbVendas.getSelectedRow();
        int codigoVenda = (int) jTbVendas.getValueAt(linha, 0);
        listaModelProdutos = new ArrayList<>();
        listaModelProdutosVendasProdutos = controllerProdutosVendasProdutos.getListaProdutosVendasProdutosController(codigoVenda);
        for (int i = 0; i < listaModelProdutosVendasProdutos.size(); i++) {
            modelProdutos = new ModelProduto();
            modelProdutos.setIdProduto(listaModelProdutosVendasProdutos.get(i).getModelProdutos().getIdProduto());
            modelProdutos.setProEstoque(
                    listaModelProdutosVendasProdutos.get(i).getModelProdutos().getProEstoque()
                    + listaModelProdutosVendasProdutos.get(i).getModelVendasProdutos().getVenProQuantidade());
            listaModelProdutos.add(modelProdutos);
        }
        if (controllerProdutos.atualizarEstoqueProdutoController(listaModelProdutos)) {
            controllerVendasProdutos.excluirVendasProdutosController(codigoVenda);
            if (controllerVendas.excluirVendasController(codigoVenda)) {
                JOptionPane.showMessageDialog(this, "Venda Excluida!", "SUCESSO", JOptionPane.WARNING_MESSAGE);
                this.carregarVendas();
                 this.desabilitaHabilitaCampos(false);
               this.  limparFormulario();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao excluir a venda", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao excluir a venda", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtExcluirActionPerformed

    private void jBTAdicionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTAdicionarProdutoActionPerformed
        // TODO add your handling code here:
        if (jTFQuantidade.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo quantidade não pode ser vazio!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
        } else {
            modelProdutos = controllerProdutos.getProdutoController(Integer.parseInt(jTFCodigoProduto.getText()));
            //adiciona uma linha na tabela
            DefaultTableModel modelo = (DefaultTableModel) jTbProdutosVenda.getModel();
            int cont = 0;
            double quantidade = 0;
            quantidade = Double.parseDouble(jTFQuantidade.getText());
            for (int i = 0; i < cont; i++) {
                modelo.setNumRows(0);
            }

            modelo.addRow(new Object[]{
                modelProdutos.getIdProduto(),
                modelProdutos.getProNome(),
                jTFQuantidade.getText(),
                modelProdutos.getProValor(),
                quantidade * modelProdutos.getProValor()
            });
            somarValorTotalProdutos();
        }
    }//GEN-LAST:event_jBTAdicionarProdutoActionPerformed

    private void jBtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtSalvarActionPerformed
        int codigoVenda = 0, codigoProduto = 0;
        double desconto = 0.0;
        listaModelVendasProdutos = new ArrayList<>();

        if (jTfDesconto.getText().equals("")) {
            desconto = 0.0;
        } else {
            desconto = Double.parseDouble(jTfDesconto.getText());
        }
        if (!jTFNumeroVendas.getText().equals("")) {
            modelVendas.setIdVenda(Integer.parseInt(jTFNumeroVendas.getText()));
        }
        modelVendas.setCliente(Integer.parseInt(jTFCodigoCliente.getText()));
        try {
            modelVendas.setVenDataVenda(blDatas.converterDataParaDateUS(new java.util.Date(System.currentTimeMillis())));
        } catch (Exception ex) {
        }
        modelVendas.setVenValorLiquido(Double.parseDouble(jTfValorTotal.getText()));
        modelVendas.setVenValorBruto(Double.parseDouble(jTfValorTotal.getText()) + desconto);

        modelVendas.setVenDesconto(desconto);

        if (alterarSalvar.equals("salvar")) {
            //salva
            codigoVenda = controllerVendas.salvarVendasController(modelVendas);
            if (codigoVenda > 0) {
                JOptionPane.showMessageDialog(this, "Venda Salva!", "SUCESSO", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao salvar a venda", "ERRO", JOptionPane.ERROR_MESSAGE);
            }

            int cont = jTbProdutosVenda.getRowCount();
            for (int i = 0; i < cont; i++) {
                codigoProduto = (int) jTbProdutosVenda.getValueAt(i, 0);
                modelVendasProdutos = new ModelVendasProdutos();
                modelProdutos = new ModelProduto();
                modelVendasProdutos.setProduto(codigoProduto);
                modelVendasProdutos.setVendas(codigoVenda);
                modelVendasProdutos.setVenProValor((double) jTbProdutosVenda.getValueAt(i, 3));
                modelVendasProdutos.setVenProQuantidade(Integer.parseInt(jTbProdutosVenda.getValueAt(i, 2).toString()));
                //produto
                modelProdutos.setIdProduto(codigoProduto);
                modelProdutos.setProEstoque(controllerProdutos.getProdutoController(codigoProduto).getProEstoque()
                        - Integer.parseInt(jTbProdutosVenda.getValueAt(i, 2).toString()));
                listaModelVendasProdutos.add(modelVendasProdutos);
                listaModelProdutos.add(modelProdutos);
            }
            //salvar os produtos da venda
            if (controllerVendasProdutos.salvarVendasProdutosController(listaModelVendasProdutos)) {
                //Alterar estoque de produtos;
                controllerProdutos.atualizarEstoqueProdutoController(listaModelProdutos);
//                JOptionPane.showMessageDialog(this, "Produtos da venda  Salvo(s)!", "SUCESSO", JOptionPane.WARNING_MESSAGE);
                carregarVendas();
                limparFormulario();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao salvar produto da  venda", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            //altera
            //Inicio Retornar Para o Estoque e excluir produtos da Venda
            int linha = jTbVendas.getSelectedRow();
            codigoVenda = (int) jTbVendas.getValueAt(linha, 0);
            listaModelProdutos = new ArrayList<>();
            listaModelProdutosVendasProdutos = controllerProdutosVendasProdutos.getListaProdutosVendasProdutosController(codigoVenda);
            for (int i = 0; i < listaModelProdutosVendasProdutos.size(); i++) {
                modelProdutos = new ModelProduto();
                modelProdutos.setIdProduto(listaModelProdutosVendasProdutos.get(i).getModelProdutos().getIdProduto());
                modelProdutos.setProEstoque(
                        listaModelProdutosVendasProdutos.get(i).getModelProdutos().getProEstoque()
                        + listaModelProdutosVendasProdutos.get(i).getModelVendasProdutos().getVenProQuantidade());
                listaModelProdutos.add(modelProdutos);
            }
            if (controllerProdutos.atualizarEstoqueProdutoController(listaModelProdutos)) {
                if (controllerVendasProdutos.excluirVendasProdutosController(codigoVenda)) {

//                    JOptionPane.showMessageDialog(this, "Venda Excluida!", "SUCESSO", JOptionPane.WARNING_MESSAGE);
                    this.carregarVendas();
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao excluir a venda", "ERRO", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao excluir a venda", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
            //Fim Retornar Para o Estoque e excluir produtos da Venda

            if (controllerVendas.atualizarVendasController(modelVendas)) {
                JOptionPane.showMessageDialog(this, "Venda Alterada!", "SUCESSO", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao alterar a venda", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
            //Adicionar produtos na lista para salvar
            int cont = jTbProdutosVenda.getRowCount();
            for (int i = 0; i < cont; i++) {
                codigoProduto = (int) jTbProdutosVenda.getValueAt(i, 0);
                modelVendasProdutos = new ModelVendasProdutos();
                modelProdutos = new ModelProduto();
                modelVendasProdutos.setProduto(codigoProduto);
                modelVendasProdutos.setVendas(codigoVenda);
                modelVendasProdutos.setVenProValor((double) jTbProdutosVenda.getValueAt(i, 3));
                modelVendasProdutos.setVenProQuantidade(Integer.parseInt(jTbProdutosVenda.getValueAt(i, 2).toString()));
                //produto
                modelProdutos.setIdProduto(codigoProduto);
                modelProdutos.setProEstoque(controllerProdutos.getProdutoController(codigoProduto).getProEstoque()
                        - Integer.parseInt(jTbProdutosVenda.getValueAt(i, 2).toString()));
                listaModelVendasProdutos.add(modelVendasProdutos);
                listaModelProdutos.add(modelProdutos);
            }
            //Salvar os produtos da venda
            if (controllerVendasProdutos.salvarVendasProdutosController(listaModelVendasProdutos)) {
//                JOptionPane.showMessageDialog(this, "Produtos da venda  Salvo(s)!", "SUCESSO", JOptionPane.WARNING_MESSAGE);
                carregarVendas();
                limparFormulario();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao salvar produto da  venda", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }
            jBtSalvar.setEnabled(false);
    }//GEN-LAST:event_jBtSalvarActionPerformed

    private void jBtAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAlterarActionPerformed
        // TODO add your handling code here:
        //habilitar botão novopara alterar
        //setar varivel alterarSalvar para alterar
        alterarSalvar = "alterar";
        int linha = jTbVendas.getSelectedRow();
        int codigoVenda = (int) jTbVendas.getValueAt(linha, 0);
        listaModelProdutosVendasProdutos = controllerProdutosVendasProdutos.getListaProdutosVendasProdutosController(codigoVenda);
        DefaultTableModel modelo = (DefaultTableModel) jTbProdutosVenda.getModel();
        modelo.setNumRows(0);
        for (int i = 0; i < listaModelProdutosVendasProdutos.size(); i++) {
            jTFNumeroVendas.setText(String.valueOf(listaModelProdutosVendasProdutos.get(i).getModelVendasProdutos().getVendas()));
            modelo.addRow(new Object[ ]{
                listaModelProdutosVendasProdutos.get(i).getModelProdutos().getIdProduto(),
                listaModelProdutosVendasProdutos.get(i).getModelProdutos().getProNome(),
                listaModelProdutosVendasProdutos.get(i).getModelVendasProdutos().getVenProQuantidade(),
                listaModelProdutosVendasProdutos.get(i).getModelVendasProdutos().getVenProValor(),
                listaModelProdutosVendasProdutos.get(i).getModelVendasProdutos().getVenProQuantidade()
                * listaModelProdutosVendasProdutos.get(i).getModelVendasProdutos().getVenProValor()
            });
        }
        somarValorTotalProdutos();
        jTbPCadastroConsutarExcluirAlterar.setSelectedIndex(0);
        jBtSalvar.setEnabled(true);
        jBTAdicionarProduto.setEnabled(true);
        jBtRemover.setEnabled(true);
        jBtNovo.setEnabled(false);
         jTFQuantidade.setText(String.valueOf(1));
            jTFCodigoCliente.setEnabled(true);
        uJCBNomeDoCliente.setEnabled(true);
        jTFCodigoProduto.setEnabled(true);
        uJCBoxNomeProduto.setEnabled(true);
        jTFQuantidade.setEnabled(true);
        jTfDesconto.setEnabled(true);
        jTfValorTotal.setEnabled(true);
         listarClientes();
        listarProdutos();
        preencherCodigoClientePeloCombobok();
        preencherCodigoProdutoPeloCombobox();
        
    }//GEN-LAST:event_jBtAlterarActionPerformed

    private void jBtRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtRemoverActionPerformed
        // TODO add your handling code here:
        int linha = jTbProdutosVenda.getSelectedRow();
        DefaultTableModel modelo = (DefaultTableModel) jTbProdutosVenda.getModel();
        modelo.removeRow(linha);
        somarValorTotalProdutos();
    }//GEN-LAST:event_jBtRemoverActionPerformed

    private void uJCBoxNomeProdutoPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_uJCBoxNomeProdutoPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if (uJCBoxNomeProduto.isPopupVisible()) {
            preencherCodigoProdutoPeloCombobox();
        }
    }//GEN-LAST:event_uJCBoxNomeProdutoPopupMenuWillBecomeInvisible

    private void uJCBNomeDoClientePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_uJCBNomeDoClientePopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if (uJCBNomeDoCliente.isPopupVisible()) {
            preencherCodigoClientePeloCombobok();
        }
    }//GEN-LAST:event_uJCBNomeDoClientePopupMenuWillBecomeInvisible

    private void jBtImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtImprimirActionPerformed
        // TODO add your handling code here:
        int linha = jTbVendas.getSelectedRow();
        int codigoVenda = (int) jTbVendas.getValueAt(linha, 0);
        final ViewAguarde carregando = new ViewAguarde();
        carregando.setVisible(true);
        Thread t = new Thread() {

            public void run() {
                //método de imprimir
                try {
                    controllerVendas.gerarRelatorioVenda(codigoVenda);
                    carregando.dispose();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Erro ao gerar relatório! /n " + e, "ERRO", JOptionPane.ERROR_MESSAGE);
                }
            }
        };
        t.start();
    }//GEN-LAST:event_jBtImprimirActionPerformed

    private void jBtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCancelarActionPerformed
        desabilitaHabilitaCampos(false);
        limparFormulario();
    }//GEN-LAST:event_jBtCancelarActionPerformed

    private void jTbVendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbVendasMouseClicked
        jBtAlterar.setEnabled(true);
        jBtExcluir.setEnabled(true);
        jBtImprimir.setEnabled(true);
        jBtPesquisar.setEnabled(true);
        jBtCancelar.setEnabled(true);
    }//GEN-LAST:event_jTbVendasMouseClicked

    private void jTFCodigoProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFCodigoProdutoFocusLost
        // TODO add your handling code here:
        modelProdutos = controllerProdutos.getProdutoController(Integer.parseInt(jTFCodigoProduto.getText()));
        uJCBoxNomeProduto.setSelectedItem(modelProdutos.getProNome());
    }//GEN-LAST:event_jTFCodigoProdutoFocusLost

    private void jTFCodigoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCodigoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFCodigoClienteActionPerformed

    private void jTFCodigoClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFCodigoClienteFocusLost
        // TODO add your handling code here:
        modelCliente = controllerCliente.getClienteController(Integer.parseInt(jTFCodigoCliente.getText()));
        uJCBNomeDoCliente.setSelectedItem(modelCliente.getCliNome());
    }//GEN-LAST:event_jTFCodigoClienteFocusLost

    private void jTfDescontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTfDescontoFocusLost
       somarValorTotalProdutos();
    }//GEN-LAST:event_jTfDescontoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewVendas().setVisible(true);
            }
        });
    }

    /**
     * Preenche o comboBox com todos os clientes
     */
    private void listarClientes() {
        listaModelCliente = controllerCliente.getListaClienteController();
        uJCBNomeDoCliente.removeAllItems();
        for (int i = 0; i < listaModelCliente.size(); i++) {
            uJCBNomeDoCliente.addItem(listaModelCliente.get(i).getCliNome());
        }
    }

    private void preencherCodigoProdutoPeloCombobox() {
        modelProdutos = controllerProdutos.getProdutoController(uJCBoxNomeProduto.getSelectedItem().toString());
        jTFCodigoProduto.setText(String.valueOf(modelProdutos.getIdProduto()));
    }

    private void preencherCodigoClientePeloCombobok() {
        modelCliente = controllerCliente.getClienteController(uJCBNomeDoCliente.getSelectedItem().toString());
        jTFCodigoCliente.setText(String.valueOf(modelCliente.getIdCliente()));
    }

    /**
     * Preencher comboBox produtos
     */
    private void listarProdutos() {
        listaModelProdutos = controllerProdutos.getListaProdutoController();
        uJCBoxNomeProduto.removeAllItems();
        for (int i = 0; i < listaModelProdutos.size(); i++) {
            uJCBoxNomeProduto.addItem(listaModelProdutos.get(i).getProNome());
        }
    }

    /**
     * Aplica descontos ao valor final da venda
     */
    private void aplicarDesconto() {
        try {
            jTfValorTotal.setText(String.valueOf(Double.parseDouble(jTfValorTotal.getText()) - Double.parseDouble(jTfDesconto.getText())));
        } catch (NumberFormatException e) {
        }
    }

    /**
     * Soma todos os produtos da venda
     */
    private void somarValorTotalProdutos() {
        double soma = 0, valor;
        int cont = jTbProdutosVenda.getRowCount();

        for (int i = 0; i < cont; i++) {
            valor = (double) jTbProdutosVenda.getValueAt(i, 4);
            soma += valor;
        }
        jTfValorTotal.setText(String.valueOf(soma));
        aplicarDesconto();
    }

    private void carregarVendas() {
        DefaultTableModel modelo = (DefaultTableModel) jTbVendas.getModel();
        listaModelVendasClientes = controllerVendasCliente.getListaVendasClienteController();
        int cont = listaModelVendasClientes.size();
        modelo.setNumRows(0);
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
                listaModelVendasClientes.get(i).getModelVendas().getIdVenda(),
                listaModelVendasClientes.get(i).getModelClientes().getCliNome(),
                listaModelVendasClientes.get(i).getModelVendas().getVenDataVenda()
            });
        }
    }

    /**
     * Limpar formulário de venda
     */
    private void limparFormulario() {
        jTFQuantidade.setText("");
        jTfDesconto.setText("");
        jTfValorTotal.setText("");
        jTFCodigoCliente.setText("");
        jTFCodigoProduto.setText("");
        jTFNumeroVendas.setText("");
        uJCBNomeDoCliente.clear();
        uJCBoxNomeProduto.clear();
        DefaultTableModel modelo = (DefaultTableModel) jTbProdutosVenda.getModel();
        modelo.setNumRows(0);
        
    }
    
      private void desabilitaHabilitaCampos(boolean condicao) {
        jTFCodigoCliente.setEnabled(condicao);
        uJCBNomeDoCliente.setEnabled(condicao);
        jTFCodigoProduto.setEnabled(condicao);
        uJCBoxNomeProduto.setEnabled(condicao);
        jTFQuantidade.setEnabled(condicao);
        jTFNumeroVendas.setEnabled(condicao);
        jBTAdicionarProduto.setEnabled(condicao);
        jBtRemover.setEnabled(condicao);
        jBtSalvar.setEnabled(condicao);
        jBtCancelar.setEnabled(condicao);
        jTfDesconto.setEnabled(condicao);
        jTfValorTotal.setEnabled(condicao);
        jBtAlterar.setEnabled(condicao);
        jBtExcluir.setEnabled(condicao);
        jBtImprimir.setEnabled(condicao);
        jBtPesquisar.setEnabled(condicao);        
      }  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTAdicionarProduto;
    private javax.swing.JButton jBtAlterar;
    private javax.swing.JButton jBtCancelar;
    private javax.swing.JButton jBtExcluir;
    private javax.swing.JButton jBtImprimir;
    private javax.swing.JButton jBtNovo;
    private javax.swing.JButton jBtPesquisar;
    private javax.swing.JButton jBtRemover;
    private javax.swing.JButton jBtSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTFCodigoCliente;
    private javax.swing.JTextField jTFCodigoProduto;
    private javax.swing.JFormattedTextField jTFNumeroVendas;
    private javax.swing.JFormattedTextField jTFQuantidade;
    private javax.swing.JTabbedPane jTbPCadastroConsutarExcluirAlterar;
    private javax.swing.JTable jTbProdutosVenda;
    private javax.swing.JTable jTbVendas;
    private javax.swing.JFormattedTextField jTfDesconto;
    private javax.swing.JTextField jTfPesquisa;
    private javax.swing.JTextField jTfValorTotal;
    private componentes.UJComboBox uJCBNomeDoCliente;
    private componentes.UJComboBox uJCBoxNomeProduto;
    // End of variables declaration//GEN-END:variables
}
